baseURL = "https://code-with-the-italians.github.io"
languageCode = "en-us"
title = "Code with the Italians"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Navbar Menus
[[menu.main]]
name    = "Home"
url     = "/"
weight  = 1
[[menu.main]]
name    = "About"
url     = "about"
weight  = 2

# Site Params
[params]
home = "Home"
logo = "images/logo.png"
dateFormat = "6 January 2006"
# Meta data
description = "We code live on Twitch, learning and sharing as we go"
author = "Themefisher"
# Google Analitycs
googleAnalitycsID = "G-6GC9HZ94VP"
# contact form action
contactFormAction = "#" # contact form works with https://formspree.io

# Banner Section
[params.banner]
enable  = true
bgImage = "images/slider.jpg"
heading = "WELCOME TO CODE WITH THE ITALIANS"
description = "WE BUILD APPS IN THE WILD, STREAMING OUR LIVE CODING SESSIONS ON TWITCH"
# button
btn     = true
btnText = "Watch live"
btnURL  = "https://twitch.codewiththeitalians.it"

# flip text
[[params.banner.flipText]]
title   = "ANDROID"
[[params.banner.flipText]]
title   = "COMPOSE"
[[params.banner.flipText]]
title   = "KOTLIN"

# Homepage About Section
[params.about]
enable  = true
title   = "Why / What / How"
content = "We are always looking for new things to learn, share with the community and expand our comfort zone.</br></br>We wanted to dive into Jetpack Compose, learning how it's differnt frome the current Android standard way of building an app.</br></br>We want to make it clear that we are learning as we go so we are streaming our live coding sessions."
image   = "images/about/about.jpg"

# Call to Action
[params.cta]
enable  = false
title   = "SO WHAT YOU THINK ?"
content = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis,<br>possimus commodi, fugiat magnam temporibus vero magni recusandae? Dolore, maxime praesentium."
btnText = "Contact with me"
btnURL  = "/contact"

# Portfolio Section On Homepage
[params.portfolio]
enable  = false
title   = "Projects"
subtitle= "What are we working on at the moment and what we did in the past"

# social icon
[[params.socialIcon]]
icon = "ion-social-twitter"
url = "https://twitter.com/codewiththeita"

[[params.socialIcon]]
icon = "ion-social-github"
url = "https://github.com/rock3r/bundel"

[[params.socialIcon]]
icon = "ion-social-youtube"
url = "https://youtube.codewiththeitalians.it"

[[params.socialIcon]]
icon = "ion-social-twitch"
url = "https://twitch.codewiththeitalians.it"